apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"ApplicationSet","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"cluster-addons"},"name":"external-dns-appset","namespace":"argocd"},"spec":{"generators":[{"matrix":{"generators":[{"merge":{"generators":[{"clusters":{"values":{"chart_version":"1.14.5"}}},{"clusters":{"selector":{"matchLabels":{"environment":"staging"}},"values":{"chart_version":"1.14.5"}}}],"mergeKeys":["name"]}},{"git":{"directories":[{"path":"gitops-bridge/environments/*/external-dns"}],"repoURL":"https://github.com/JoeKer1/td-argotest.git","revision":"main"}}],"mergeKeys":["name","path.components.2"]}}],"template":{"metadata":{"annotations":null,"name":"{{name}}-externaldns"},"spec":{"destination":{"namespace":"ingress-nginx","server":"{{server}}"},"project":"default","sources":[{"ref":"values","repoURL":"{{metadata.annotations.addons_repo_url}}","targetRevision":"main"},{"chart":"external-dns","helm":{"ignoreMissingValueFiles":true,"releaseName":"external-dns","valueFiles":["$values/gitops-bridge/environments/default/external-dns/values.yaml","$values/gitops-bridge/environments/{{name}}/external-dns/values.yaml"]},"repoURL":"https://kubernetes-sigs.github.io/external-dns","targetRevision":"{{values.chart_version}}"}],"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}}}
  creationTimestamp: "2025-04-06T23:45:57Z"
  generation: 3
  labels:
    argocd.argoproj.io/instance: cluster-addons
  name: external-dns-appset
  namespace: argocd
  resourceVersion: "25352"
  uid: 5413a795-74cb-430c-91bb-44f40d2376ca
spec:
  generators:
  - matrix:
      generators:
      - merge:
          generators:
          - clusters:
              values:
                chart_version: 1.14.5
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                chart_version: 1.14.5
          mergeKeys:
          - name
      - git:
          directories:
          - path: gitops-bridge/environments/*/external-dns
          repoURL: https://github.com/JoeKer1/td-argotest.git
          revision: main
  template:
    metadata:
      name: '{{name}}-externaldns'
    spec:
      destination:
        namespace: ingress-nginx
        server: '{{server}}'
      project: default
      sources:
      - ref: values
        repoURL: '{{metadata.annotations.addons_repo_url}}'
        targetRevision: main
      - chart: external-dns
        helm:
          ignoreMissingValueFiles: true
          releaseName: external-dns
          valueFiles:
          - $values/gitops-bridge/environments/default/external-dns/values.yaml
          - $values/gitops-bridge/environments/{{name}}/external-dns/values.yaml
        repoURL: https://kubernetes-sigs.github.io/external-dns
        targetRevision: '{{values.chart_version}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
status:
  conditions:
  - lastTransitionTime: "2025-04-06T23:57:14Z"
    message: Successfully generated parameters for all Applications
    reason: ApplicationSetUpToDate
    status: "False"
    type: ErrorOccurred
  - lastTransitionTime: "2025-04-06T23:57:14Z"
    message: Successfully generated parameters for all Applications
    reason: ParametersGenerated
    status: "True"
    type: ParametersGenerated
  - lastTransitionTime: "2025-04-06T23:57:14Z"
    message: ApplicationSet up to date
    reason: ApplicationSetUpToDate
    status: "True"
    type: ResourcesUpToDate
