apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns-appset
spec:
  generators:
    - matrix:
        mergeKeys: ["name", "path.basename"]
        generators:
          - merge:
              mergeKeys: ["name"]
              generators:
                - clusters:
                    values:
                      chart_version: 1.14.5
                      addonChartRepository: 
                - clusters:
                    selector:
                      matchLabels:
                        environment: staging
                    values:
                      chart_version: 0.9.0
                - clusters:
                    selector:
                      matchLabels:
                        environment: production
                    values:
                      chart_version: 0.8.0
          - git:
              repoURL: https://github.com/JoeKer1/td-argotest.git
              revision: main
              directories:
                - path: gitops-bridge/environments/*/external-dns
  template:
    metadata:
      name: '{{name}}-externaldns'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: ingress-nginx
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: main
          ref: values
        - repoURL: https://kubernetes-sigs.github.io/external-dns
          chart: external-dns
          releaseName: 'external-dns'
          ignoreMissingValueFiles: true
          targetRevision: '{{values.chart_version}}'
          helm:
            valueFiles:
              - $values/gitops-bridge/environments/default/external-dns/values.yaml                    # default values
              - $values/gitops-bridge/environments/clusters/{{name}}/external-dns/values.yaml          # cluster-specific
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true