apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns-appset
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/JoeKer1/td-argotest.git
              revision: main
              directories:
                - path: gitops-bridge/environments/*/external-dns
          - merge:
              mergeKeys:
                - name
              generators:
                - clusters:
                    values:
                      chart_version: 1.14.5
                - clusters:
                    selector:
                      matchLabels:
                        environment: staging
                    values:
                      chart_version: 1.14.4
  template:
    metadata:
      name: '{{name}}-externaldns'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: ingress-nginx
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: main
          ref: values
        - repoURL: https://kubernetes-sigs.github.io/external-dns
          chart: external-dns
          targetRevision: '{{values.chart_version}}'
          helm:
            releaseName: external-dns
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/gitops-bridge/environments/default/external-dns/values.yaml
              - $values/gitops-bridge/environments/{{path.basename}}/external-dns/values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
